#!/usr/bin/env bash

if [ $# -lt 3 ]; then
echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
exit 1
fi

FILE_PATH="$1"
SERVER_IP="$2"
USER_NAME="$3"
SSH="$4"
SCP_OPTIONS="-o StrictHostKeyChecking=no"
scp $SCP_OPTIONS -i "$SSH" "$FILE_PATH" "$USER_NAME@$SERVER_IP:~/"
