#!/usr/bin/env bash
# this how we transfer file to server securly with scp
# we got arguments from temrinal
# scp [file_name]  remoteuser@remotehost:/remote/directory
# # scp test.txt jayesh@10.143.90.2:/home/jayesh

if [ $# -lt 3 ]
then
echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
path=$1
ip=$2
username=$3
pathtossh=$4
scp -i $pathtossh -o StrictHostKeyChecking=no $path $username@$ip:~/
fi
