#!/usr/bin/env bash
# this how to install nginx in web server

sudo apt-get update -y
sudo apt-get install nginx -y
sudo service nginx start
# allowing nginx on firewall
sudo ufw allow 'Nginx HTTP'
sudo sh -c 'echo "Hello World!" > /var/www/html/index.nginx-debian.html'
sudo service nginx restart

