#!/usr/bin/env bash
# this sed command to add redirect permenant to any thing here we redirect it to youtube video 
sudo sed -i '24i\       rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
sudo service nginx restart
