#!/usr/bin/env bash
# configure new ubuntu machine
# then make redirect to youtube video
# add error page to the var/www/html
# add line to make the error page listen to this page
sudo apt-get update -y
sudo apt-get install nginx -y
sudo service nginx start
# allowing nginx on firewall
sudo ufw allow 'Nginx HTTP'
sudo sh -c 'echo "Hello World!" > /var/www/html/index.nginx-debian.html' 
sudo sed -i '24i\       rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" >> /var/www/html/error_404.html
sudo sed -i '25i\	error_page 404 /error_404.html;' /etc/nginx/sites-available/default
sudo service nginx restart
