#!/usr/bin/env bash
# this is a Haproxy install 
#hAPROXY is a load balancer


# this is install haproxy 
sudo apt install haproxy -y 


echo "ENAPLED=1" | sudo tee -a /etc/default/haproxy

cat << EOT | sudo tee -a /etc/haproxy/haproxy.cfg

frontend web_servers
  mode http
  bind :80
  default_backend web_servers_backend

backend web_servers_backend
  timeout connect  3000
  timeout server  30000
  balance roundrobin
  server 347679-web-01 52.3.220.211:80 check
  server 347679-web-02 35.175.128.66:80 check
  
EOT

sudo service haproxy restart
