#!/usr/bin/env bash
# Write a Bash script that gives you information about the school file.
file="school"
if [ -e $file ]
then
echo "school file exists"
else
echo "school file does not exist"
fi

if [ -e $file ]
then
if ! [ -s $file ]
then
echo "school file is empty"
else
echo "school file is not empty"
fi
if [ -f $file ]
then
echo "school is a regular file"
fi
fi
