#!/usr/bin/env bash
# Configure a ufw firewall to block all incoming trafic

sudo apt-get install ufw 
sudo ufw default deny incoming
sudo ufw allow 22
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp
sudo ufw enable
sudo ufw reload



